### ISSUE TITLE
Initial cleanup & improvements

### ISSUE THREAD

**Issue by rnicholus** [orlandovald/fineuploader-go-server#2]
- [x] In the "get the code" section of the README, the `go get` line should read `go get github.com/FineUploader/go-server`
- [x] Remove static directory. Replace with a package.json that pulls fine-uploader from npm.
- [x] Ensure the binary is still called `fineuploader-go-server`. I'm not exactly sure how this can be accomplished without further investigation, not being vary golang-savy myself. I'm wondering if we have to change the repo name back to "fineuploader-go-server", but I hope this is not the case.
- [x] Add a license file to the repo.
- [x] Include a short "getting started guide" section that show how to pull in Fine Uploader, start/configure the server, and configure your browser-side code as well. Focus on the items specific to the server are sufficient. May require refactoring existing bits of the README.

**Comment by orlandovald** [comment]
For the binary name, there are 2 ways of generating the binary at least that I'm aware of, `go build` and `go install`, the default behavior for both is to name the binary as the last element in the source directory when no parameters are specified. go build can take the `-o` flag to specify the binary name but most people will just run the install/build without any parameters (by navigating to the source directory first) or by specifying the source directory that holds the source file(s). I would prefer to change the repo name to keep the default name as `fineuploader-go-server` forcing the developer to manually change the binary name if that is their intention.

Since the `go build` can take a go file as a parameter as well, creating a binary with the same name as the specified go file, I would also propose to change the source file name to `fineuploader-go-server.go` to keep the same default name both when running `go build` without parameters (hence using the source directory name) or when the go file name is specified.

What do you think?

**Comment by rnicholus** [comment]
> I would prefer to change the repo name to keep the default name as fineuploader-go-server forcing the developer to manually change the binary name if that is their intention.

👍 

> I would also propose to change the source file name to fineuploader-go-server.go

👍 

Would these be breaking changes for anyone already depending on this library? I never quite understood how golang deals with breaking changes in libraries. It seems the common behavior is to "hope that everything works out", but this is just my ignorant opinion. Do you know?

**Comment by orlandovald** [comment]
Dependency management is still weak in Go but the good news is that in our case, this is actually not a library but a standalone application, so this shouldn't be used as a dependency on any other project in the strict sense of importing any package into some other Go file.

**Comment by rnicholus** [comment]
Makes sense. Thanks for the update.

**Comment by orlandovald** [comment]
@rnicholus when you get a chance, can you check the package.json and the updated README to see if everything makes sense before closing this issue and merging to master?

**Comment by rnicholus** [comment]
I added some comments to your commits in the development branch. Please let me know if you have any questions.
